version: '3.8'

services:
  high-command:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: high-command
    environment:
      - X_SUPER_CLIENT=hc.dataknife.ai
      - X_SUPER_CONTACT=lee@fullmetal.dev
      - LOG_LEVEL=INFO
    volumes:
      - ./mcp:/app/mcp
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
